import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth";

// - You import **NextAuth**, which handles all login/logout/auth callbacks.
// - You import your custom configuration `authOptions` (providers, callbacks, secret, adapter, etc.) from:

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };

// This file:
// 	•	Loads your NextAuth configuration
// 	•	Creates an API route that can process login/logout/session-related requests
// 	•	Exposes the same NextAuth handler for both GET and POST methods
// 	•	Allows NextAuth to work inside the Next.js App Router (app/ directory)

// - `handler` is a function generated by NextAuth
// - It knows how to respond to:
//   - GET requests (session, providers)
//   - POST requests (sign in, sign out, callback)

// So now `handler` is your entire authentication backend.